server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/File
    username: postgres
    password: 12345
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  codec:
    max-in-memory-size: 1GB
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update